using System.Text.Json;

namespace Cis.Modules.Design;

internal sealed record WireframeScreen(string Id, string FrontendType, string Name, string Route, string Platform, string Purpose);

internal static class DesignRendererScaffolder
{
    // Definition previews and governed delivery designs share the same control primitives.
    internal static string ControlPrimitives => Template[Template.IndexOf("function esc(", StringComparison.Ordinal)..Template.IndexOf("function pageHeader(", StringComparison.Ordinal)];

    public static string Render(
        string feature,
        IReadOnlyList<WireframeScreen> screens,
        string shell,
        IReadOnlyList<string> components,
        string guidelinePath,
        string guidelineSha256,
        string uiDirectionPath,
        string uiDirectionSha256,
        string wireframeSha256)
    {
        var options = new JsonSerializerOptions { WriteIndented = true };
        var screenJson = JsonSerializer.Serialize(screens.Select(screen => new
        {
            id = Slug(screen.Id),
            frontendType = screen.FrontendType,
            name = screen.Name,
            route = screen.Route,
            platform = screen.Platform,
            purpose = screen.Purpose,
            state = "primary",
            viewport = "desktop",
            file = $"{Slug(screen.Id)}--primary--desktop.png",
        }), options);
        var componentJson = JsonSerializer.Serialize(components.Distinct(StringComparer.OrdinalIgnoreCase), options);
        return Template
            .Replace("__FEATURE__", EscapeJs(feature), StringComparison.Ordinal)
            .Replace("__SHELL__", EscapeJs(shell), StringComparison.Ordinal)
            .Replace("__COMPONENTS__", componentJson, StringComparison.Ordinal)
            .Replace("__SCREENS__", screenJson, StringComparison.Ordinal)
            .Replace("__GUIDELINE_PATH__", EscapeJs(guidelinePath), StringComparison.Ordinal)
            .Replace("__GUIDELINE_SHA__", EscapeJs(guidelineSha256), StringComparison.Ordinal)
            .Replace("__UI_DIRECTION_PATH__", EscapeJs(uiDirectionPath), StringComparison.Ordinal)
            .Replace("__UI_DIRECTION_SHA__", EscapeJs(uiDirectionSha256), StringComparison.Ordinal)
            .Replace("__WIREFRAME_SHA__", EscapeJs(wireframeSha256), StringComparison.Ordinal);
    }

    private static string Slug(string value)
    {
        var chars = value.Trim().ToLowerInvariant().Select(character =>
            char.IsLetterOrDigit(character) ? character : '-').ToArray();
        return string.Join('-', new string(chars).Split('-', StringSplitOptions.RemoveEmptyEntries));
    }

    private static string EscapeJs(string value)
        => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);

    private const string Template = """
// Generated by CIS design templates. This file is the self-contained canonical design source.
// Do not split layout, styles, data, shell, or components into companion source files.
import { mkdirSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const sharpNodeModules = process.env.CIS_SHARP_NODE_MODULES;
if (!sharpNodeModules) throw new Error("Sharp runtime unavailable. Run through `cis design render` from an initialized workspace containing Sharp.");
const sharp = createRequire(path.join(sharpNodeModules, "..", "cis-design-runtime.cjs"))("sharp");

const feature = "__FEATURE__";
const width = 1600;
const height = 1000;
const outputDirectory = path.dirname(fileURLToPath(import.meta.url));
const provenance = Object.freeze({
  wireframeSha256: "__WIREFRAME_SHA__",
  guidelinePath: "__GUIDELINE_PATH__",
  guidelineSha256: "__GUIDELINE_SHA__",
  uiDirectionPath: "__UI_DIRECTION_PATH__",
  uiDirectionSha256: "__UI_DIRECTION_SHA__",
  shellTemplate: "__SHELL__@1.0",
  componentTemplates: __COMPONENTS__,
});
const screens = Object.freeze(__SCREENS__);
const minimalShell = provenance.shellTemplate.startsWith("shell.minimal-app@");
const canvasX = minimalShell ? 64 : 324;
const canvasWidth = minimalShell ? 1472 : 1210;

const tokens = Object.freeze({
  bg: "#FFFFFF", soft: "#F8FAFC", dark: "#0F172A", slate: "#334155",
  muted: "#64748B", border: "#CBD5E1", blue: "#2563EB", teal: "#0F766E",
  success: "#15803D", warning: "#B45309", critical: "#B91C1C",
  radiusSm: 8, radiusMd: 12, radiusLg: 16,
  space1: 8, space2: 16, space3: 24, space4: 32, space5: 48, space6: 64,
});

function esc(value) {
  return String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}
function rect(x, y, w, h, fill = tokens.bg, stroke = tokens.border, radius = tokens.radiusSm) {
  return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${radius}" fill="${fill}" stroke="${stroke}"/>`;
}
function text(value, x, y, size = 16, fill = tokens.dark, weight = 400, extra = "") {
  return `<text x="${x}" y="${y}" font-family="Inter, Segoe UI, Arial, sans-serif" font-size="${size}" font-weight="${weight}" fill="${fill}" ${extra}>${esc(value)}</text>`;
}
function line(x1, y1, x2, y2, stroke = tokens.border) {
  return `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${stroke}"/>`;
}
function standardButton(label, x, y, w = 154, variant = "secondary", state = "default") {
  const palette = { primary: [tokens.blue, tokens.bg, tokens.blue], secondary: [tokens.bg, tokens.dark, tokens.border],
    destructive: [tokens.critical, tokens.bg, tokens.critical], ghost: ["transparent", tokens.slate, "transparent"] };
  let [fill, ink, stroke] = palette[variant] ?? palette.secondary;
  if (state === "disabled") [fill, ink, stroke] = ["#E2E8F0", "#94A3B8", "#CBD5E1"];
  const prefix = state === "loading" ? "... " : "";
  const focus = state === "focused" ? `<rect x="${x - 3}" y="${y - 3}" width="${w + 6}" height="48" rx="11" fill="none" stroke="${tokens.blue}" stroke-width="2"/>` : "";
  return focus + rect(x, y, w, 42, fill, stroke, tokens.radiusSm)
    + text(prefix + label, x + 16, y + 27, 14, ink, 650);
}
function textInput(label, value, x, y, w = 320, state = "default", helper = "") {
  const stroke = state === "error" ? tokens.critical : state === "focused" ? tokens.blue : tokens.border;
  const fill = state === "disabled" ? "#F1F5F9" : tokens.bg;
  let svg = text(label, x, y, 13, tokens.slate, 650) + rect(x, y + 10, w, 44, fill, stroke, tokens.radiusSm)
    + text(value || "Enter a value", x + 14, y + 38, 14, value ? tokens.dark : tokens.muted, 400);
  if (helper) svg += text(helper, x, y + 74, 12, state === "error" ? tokens.critical : tokens.muted, 400);
  return svg;
}
function selectInput(label, value, x, y, w = 320, state = "default") {
  const stroke = state === "error" ? tokens.critical : state === "focused" || state === "open" ? tokens.blue : tokens.border;
  let svg = text(label, x, y, 13, tokens.slate, 650) + rect(x, y + 10, w, 44, state === "disabled" ? "#F1F5F9" : tokens.bg, stroke, tokens.radiusSm)
    + text(value || "Select an option", x + 14, y + 38, 14, value ? tokens.dark : tokens.muted, 400)
    + text("v", x + w - 24, y + 38, 14, tokens.slate, 650);
  if (state === "open") svg += rect(x, y + 60, w, 116, tokens.bg, tokens.border, tokens.radiusSm)
    + ["First option", "Second option", "Third option"].map((item, index) => text(item, x + 14, y + 88 + index * 32, 13, tokens.dark, index === 0 ? 650 : 400)).join("");
  return svg;
}
function textArea(label, value, x, y, w = 480, state = "default") {
  const stroke = state === "error" ? tokens.critical : state === "focused" ? tokens.blue : tokens.border;
  return text(label, x, y, 13, tokens.slate, 650) + rect(x, y + 10, w, 104, tokens.bg, stroke, tokens.radiusSm)
    + text(value || "Enter details", x + 14, y + 38, 14, value ? tokens.dark : tokens.muted, 400)
    + text(`${(value || "").length}/500`, x + w - 52, y + 134, 11, tokens.muted, 400);
}
function checkboxControl(label, x, y, state = "unchecked") {
  const checked = state === "checked" || state === "indeterminate";
  let svg = rect(x, y, 20, 20, checked ? tokens.blue : tokens.bg, checked ? tokens.blue : tokens.border, 4);
  if (state === "checked") svg += `<path d="M ${x + 4} ${y + 10} L ${x + 8} ${y + 15} L ${x + 16} ${y + 5}" fill="none" stroke="${tokens.bg}" stroke-width="2"/>`;
  if (state === "indeterminate") svg += line(x + 5, y + 10, x + 15, y + 10, tokens.bg);
  return svg + text(label, x + 30, y + 16, 13, state === "disabled" ? "#94A3B8" : tokens.slate, 500);
}
function radioGroup(label, options, x, y, selected = 0) {
  let svg = text(label, x, y, 13, tokens.slate, 650);
  options.forEach((option, index) => {
    const oy = y + 28 + index * 32;
    svg += `<circle cx="${x + 10}" cy="${oy}" r="9" fill="${tokens.bg}" stroke="${index === selected ? tokens.blue : tokens.border}"/>`;
    if (index === selected) svg += `<circle cx="${x + 10}" cy="${oy}" r="5" fill="${tokens.blue}"/>`;
    svg += text(option, x + 30, oy + 5, 13, tokens.slate, 500);
  });
  return svg;
}
function toggleControl(label, x, y, on = false, disabled = false) {
  const fill = disabled ? "#CBD5E1" : on ? tokens.blue : "#94A3B8";
  const knob = on ? x + 24 : x + 4;
  return rect(x, y, 44, 24, fill, fill, 12) + `<circle cx="${knob + 8}" cy="${y + 12}" r="8" fill="${tokens.bg}"/>`
    + text(label, x + 56, y + 17, 13, disabled ? "#94A3B8" : tokens.slate, 500);
}
function standardTabs(items, active, x, y) {
  let svg = line(x, y + 38, x + 600, y + 38, tokens.border);
  let cx = x;
  items.forEach(item => { const w = Math.max(86, item.length * 8 + 30); svg += text(item, cx + 12, y + 24, 13, item === active ? tokens.blue : tokens.muted, item === active ? 650 : 500);
    if (item === active) svg += `<rect x="${cx}" y="${y + 35}" width="${w}" height="3" fill="${tokens.blue}"/>`; cx += w; });
  return svg;
}
function breadcrumbs(items, x, y) {
  return items.map((item, index) => text(item, x + index * 116, y, 12, index === items.length - 1 ? tokens.dark : tokens.blue, index === items.length - 1 ? 650 : 500)
    + (index < items.length - 1 ? text("/", x + index * 116 + 96, y, 12, tokens.muted, 400) : "")).join("");
}
function pagination(x, y, page = 1, pages = 8) {
  return text(`Page ${page} of ${pages}`, x, y + 26, 13, tokens.muted, 500)
    + standardButton("Previous", x + 170, y, 104, "secondary", page === 1 ? "disabled" : "default")
    + standardButton("Next", x + 286, y, 86, "secondary", page === pages ? "disabled" : "default");
}
function dropdownMenu(x, y, items) {
  let svg = rect(x, y, 220, items.length * 38 + 16, tokens.bg, tokens.border, tokens.radiusSm);
  items.forEach((item, index) => { svg += text(item.label, x + 16, y + 29 + index * 38, 13, item.destructive ? tokens.critical : tokens.dark, 500); });
  return svg;
}
function alertBanner(title, body, x, y, w = 600, tone = "information") {
  const palette = { information: ["#EAF2FF", tokens.blue], success: ["#E8F7EE", tokens.success], warning: ["#FFF3DC", tokens.warning], error: ["#FEECEC", tokens.critical] };
  const [fill, ink] = palette[tone] ?? palette.information;
  return rect(x, y, w, 72, fill, fill, tokens.radiusSm) + `<rect x="${x}" y="${y}" width="4" height="72" fill="${ink}"/>`
    + text(title, x + 20, y + 28, 14, ink, 700) + text(body, x + 20, y + 52, 12, tokens.slate, 400);
}
function modalDialog(title, body, x = 500, y = 220, w = 600, destructive = false) {
  return rect(x, y, w, 300, tokens.bg, tokens.border, tokens.radiusLg) + text(title, x + 28, y + 48, 22, tokens.dark, 650)
    + text(body, x + 28, y + 82, 14, tokens.muted, 400) + line(x, y + 226, x + w, y + 226, tokens.border)
    + standardButton("Cancel", x + w - 286, y + 244, 116, "secondary")
    + standardButton(destructive ? "Delete" : "Confirm", x + w - 154, y + 244, 126, destructive ? "destructive" : "primary");
}
function accordion(title, body, x, y, w = 600, open = false) {
  return rect(x, y, w, open ? 126 : 52, tokens.bg, tokens.border, tokens.radiusSm)
    + text(open ? "v" : ">", x + 16, y + 32, 14, tokens.slate, 650) + text(title, x + 42, y + 32, 14, tokens.dark, 650)
    + (open ? text(body, x + 42, y + 78, 13, tokens.muted, 400) : "");
}
function avatar(label, x, y, size = 36, online = false) {
  const initials = label.split(" ").map(part => part[0]).join("").slice(0, 2).toUpperCase();
  return `<circle cx="${x + size / 2}" cy="${y + size / 2}" r="${size / 2}" fill="#DBEAFE"/>`
    + text(initials, x + size / 2, y + size / 2 + 5, 12, tokens.blue, 700, 'text-anchor="middle"')
    + (online ? `<circle cx="${x + size - 3}" cy="${y + size - 3}" r="5" fill="${tokens.success}" stroke="${tokens.bg}"/>` : "");
}
function statusBadge(label, x, y, tone = "neutral") {
  const palette = { success: ["#E8F7EE", tokens.success], warning: ["#FFF3DC", tokens.warning],
    critical: ["#FEECEC", tokens.critical], accent: ["#EAF2FF", tokens.blue], neutral: ["#EEF2F7", tokens.slate] };
  const [fill, ink] = palette[tone] ?? palette.neutral;
  const w = Math.max(88, label.length * 8 + 28);
  return rect(x, y, w, 30, fill, fill, 15) + text(label, x + 14, y + 20, 12, ink, 700);
}
function card(title, body, x, y, w, h) {
  return rect(x, y, w, h, tokens.bg, tokens.border, tokens.radiusMd)
    + text(title, x + 24, y + 34, 18, tokens.dark, 650)
    + text(body, x + 24, y + 64, 13, tokens.muted, 400);
}
function dataTable(columns, rows, x, y, w) {
  const cw = w / columns.length;
  let svg = rect(x, y, w, 70 + rows.length * 92, tokens.bg, tokens.border, tokens.radiusMd);
  const cell = (value, cx, cy, weight) => {
    const limit = Math.max(10, Math.floor((cw - 32) / 7));
    const words = String(value).split(/\s+/); const lines = [''];
    for (const word of words) {
      if (lines.at(-1).length + word.length > limit && lines.at(-1)) lines.push('');
      lines[lines.length - 1] += (lines.at(-1) ? ' ' : '') + word;
    }
    return lines.slice(0, 3).map((line, i) => text(line.slice(0, limit), cx + 16, cy + i * 17, 13, tokens.slate, weight)).join('');
  };
  columns.forEach((column, i) => { svg += cell(column, x + i * cw, y + 27, 650); });
  rows.forEach((row, i) => {
    svg += line(x, y + 70 + i * 92, x + w, y + 70 + i * 92);
    row.forEach((value, j) => { svg += cell(value, x + j * cw, y + 106 + i * 92, 400); });
  });
  return svg;
}
function pageHeader(screen, x = canvasX, w = canvasWidth) {
  return text(screen.name, x, 166, 34, tokens.dark, 650)
    + text(screen.purpose || `Design for ${feature}`, x, 198, 15, tokens.muted, 400)
    + statusBadge("Draft design", x + w - 304, 145, "accent")
    + standardButton("Primary action", x + w - 154, 140, 154, "primary");
}
function filterBar(x = canvasX, w = canvasWidth) {
  return rect(x, 250, w, 64, tokens.soft, tokens.border, tokens.radiusMd)
    + text("Search", x + 24, 289, 13, tokens.muted, 600)
    + rect(x + 94, 266, 370, 34, tokens.bg, tokens.border, tokens.radiusSm)
    + text("Search records", x + 110, 288, 13, tokens.muted, 400)
    + standardButton("Filters", x + 480, 262, 108, "secondary")
    + text("12 results", x + w - 98, 289, 13, tokens.muted, 500);
}
function standardTable(x = 324, y = 342, w = 1210) {
  const columns = ["Name", "Status", "Owner", "Updated", "Actions"];
  const widths = [390, 180, 220, 200, 140];
  let svg = rect(x, y, w, 390, tokens.bg, tokens.border, tokens.radiusMd);
  svg += `<path d="M ${x} ${y + 54} H ${x + w}" stroke="${tokens.border}"/>`;
  let cx = x + 24;
  columns.forEach((column, index) => { svg += text(column, cx, y + 34, 13, tokens.slate, 650); cx += widths[index]; });
  const rows = [
    ["Primary record", "Active", "A. Owner", "Today"],
    ["Secondary record", "Pending", "B. Reviewer", "Yesterday"],
    ["Archived record", "Archived", "C. Owner", "Last week"],
  ];
  rows.forEach((row, index) => {
    const rowY = y + 54 + index * 92;
    svg += line(x, rowY + 92, x + w, rowY + 92, "#E8EEF6");
    svg += text(row[0], x + 24, rowY + 38, 15, tokens.dark, 600);
    svg += text("Supporting evidence and concise context", x + 24, rowY + 64, 12, tokens.muted, 400);
    svg += statusBadge(row[1], x + 414, rowY + 26, index === 0 ? "success" : index === 1 ? "warning" : "neutral");
    svg += text(row[2], x + 594, rowY + 44, 13, tokens.slate, 500);
    svg += text(row[3], x + 814, rowY + 44, 13, tokens.muted, 500);
    svg += standardButton("Open", x + 1038, rowY + 24, 104, "secondary");
  });
  return svg;
}
function emptyState(title, description, x = 324, y = 342, w = 1210, h = 300) {
  return rect(x, y, w, h, tokens.bg, tokens.border, tokens.radiusMd)
    + text(title, x + w / 2, y + 122, 22, tokens.dark, 650, 'text-anchor="middle"')
    + text(description, x + w / 2, y + 156, 14, tokens.muted, 400, 'text-anchor="middle"')
    + standardButton("Primary action", x + w / 2 - 77, y + 188, 154, "primary");
}
function standardForm(x = 324, y = 250, w = 760) {
  return rect(x, y, w, 460, tokens.bg, tokens.border, tokens.radiusMd)
    + text("Details", x + 24, y + 38, 20, tokens.dark, 650)
    + textInput("Name", "", x + 24, y + 76, 340, "default", "Use a clear, recognizable name.")
    + selectInput("Category", "Select an option", x + 388, y + 76, 340)
    + textArea("Description", "", x + 24, y + 184, 704)
    + checkboxControl("I confirm the supplied information is correct", x + 24, y + 346, "unchecked")
    + standardButton("Cancel", x + w - 300, y + 390, 116, "secondary")
    + standardButton("Save", x + w - 160, y + 390, 136, "primary");
}
function timeline(x, y, items) {
  return items.map((item, index) => {
    const iy = y + index * 64;
    return `<circle cx="${x}" cy="${iy}" r="6" fill="${index === 0 ? tokens.blue : tokens.teal}"/>`
      + (index < items.length - 1 ? line(x, iy + 8, x, iy + 58, tokens.border) : "")
      + text(item, x + 20, iy + 5, 13, tokens.slate, 600);
  }).join("");
}
function applicationShell(screen, content) {
  let svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">`;
  svg += rect(0, 0, width, height, tokens.soft, tokens.soft, 0);
  if (minimalShell) {
    svg += `<rect x="0" y="0" width="${width}" height="88" fill="${tokens.dark}"/>`;
    svg += text("CIS application", canvasX, 54, 20, tokens.bg, 650);
    svg += text(screen.route || "/", width - canvasX, 54, 13, "#CBD5E1", 600, 'text-anchor="end"');
  } else {
    svg += `<rect x="0" y="0" width="270" height="${height}" fill="${tokens.dark}"/>`;
    svg += text("CIS application", 32, 54, 20, tokens.bg, 650);
    ["Overview", "Work", "Customers", "Operations", "Settings"].forEach((item, index) => {
      const y = 118 + index * 54;
      if (index === 1) svg += rect(20, y - 28, 230, 42, "#172554", "#172554", tokens.radiusSm);
      svg += text(item, 42, y, 14, index === 1 ? tokens.bg : "#CBD5E1", index === 1 ? 650 : 500);
    });
    svg += `<rect x="270" y="0" width="1330" height="88" fill="${tokens.bg}"/>`;
    svg += line(270, 88, 1600, 88, tokens.border);
    svg += text(screen.route || "/", canvasX, 54, 13, tokens.muted, 500);
    svg += text("Internal", 1450, 54, 13, tokens.slate, 600);
  }
  svg += pageHeader(screen) + content + `</svg>`;
  return svg;
}
function renderScreen(screen) {
  const useTable = provenance.componentTemplates.includes("component.table");
  const useFilters = provenance.componentTemplates.includes("component.filter-bar");
  const useForm = provenance.componentTemplates.includes("component.form");
  let content = useFilters ? filterBar() : "";
  content += useTable ? standardTable(canvasX, useFilters ? 342 : 250, canvasWidth)
    : useForm ? standardForm(canvasX, useFilters ? 342 : 250, 760)
    : card("Feature content", "Compose feature content from the reusable component catalog without changing the shared shell.", canvasX, 250, canvasWidth, 280);
  content += card("Design provenance", `${provenance.shellTemplate} · ${provenance.guidelineSha256.slice(0, 22)}…`, canvasX, 770, canvasWidth, 94);
  return applicationShell(screen, content);
}

mkdirSync(outputDirectory, { recursive: true });
for (const screen of screens) {
  const output = path.join(outputDirectory, screen.file);
  await sharp(Buffer.from(renderScreen(screen))).png().toFile(output);
  const metadata = await sharp(output).metadata();
  const stats = await sharp(output).stats();
  if (metadata.width !== width || metadata.height !== height || stats.channels.every(channel => channel.stdev === 0)) {
    throw new Error(`Invalid or blank render: ${screen.file}`);
  }
  console.log(`Rendered ${screen.file} (${metadata.width}x${metadata.height})`);
}
console.log(`Runtime node=${process.version} sharp=${sharp.versions.sharp} libvips=${sharp.versions.vips}`);
""";
}
