<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Cis.Abstractions\Cis.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Cis.Host\Cis.Host.csproj" />
    <ProjectReference Include="..\..\src\Cis.Modules.Host\Cis.Modules.Host.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
</Project>
