using System.CommandLine;using System.Text.Json;using Cis.Abstractions;using Microsoft.Extensions.DependencyInjection;
namespace Cis.Modules.Agent;
public sealed class AgentModule:ICisModule
{
 private static readonly JsonSerializerOptions J=new(JsonSerializerDefaults.Web){WriteIndented=true};public string Name=>"agent";public string Description=>"Prepare portable task envelopes and import structured agent results without granting lifecycle authority.";
 public void RegisterServices(IServiceCollection s)=>s.AddSingleton<AgentService>();public void RegisterCommands(ICisCommandRegistry c,IServiceProvider p){var s=p.GetRequiredService<AgentService>();var root=new Command(Name,Description);root.Subcommands.Add(Simple("providers","List envelope providers.",s.Providers));root.Subcommands.Add(Prepare(s));root.Subcommands.Add(Import(s));root.Subcommands.Add(Simple("status","Report envelopes and imported results.",s.Status));c.Add(root);}
 private static Command Prepare(AgentService s){var c=new Command("prepare","Prepare or refresh a task envelope.");var change=new Argument<string>("change-id");var task=new Argument<string>("task-id");var provider=new Option<string>("--provider"){DefaultValueFactory=_=>"portable"};var repo=Repo();var format=Format();c.Arguments.Add(change);c.Arguments.Add(task);c.Options.Add(provider);c.Options.Add(repo);c.Options.Add(format);c.SetAction(x=>Render(s.Prepare(x.GetValue(repo)!,x.GetValue(change)!,x.GetValue(task)!,x.GetValue(provider)!),x.GetValue(format)!));return c;}
 private static Command Import(AgentService s){var c=new Command("import-result","Import a structured result against an unchanged envelope.");var envelope=new Argument<string>("envelope");var result=new Option<string>("--result"){Required=true};var repo=Repo();var format=Format();c.Arguments.Add(envelope);c.Options.Add(result);c.Options.Add(repo);c.Options.Add(format);c.SetAction(x=>Render(s.ImportResult(x.GetValue(repo)!,x.GetValue(envelope)!,x.GetValue(result)!),x.GetValue(format)!));return c;}
 private static Command Simple(string n,string d,Func<string,AgentResult>a){var c=new Command(n,d);var r=Repo();var f=Format();c.Options.Add(r);c.Options.Add(f);c.SetAction(x=>Render(a(x.GetValue(r)!),x.GetValue(f)!));return c;}
 private static int Render(AgentResult r,string f){if(f=="json")Console.WriteLine(JsonSerializer.Serialize(r,J));else if(f=="agent"){Console.WriteLine($"status={r.Status};exitCode={r.ExitCode};providerCount={r.Providers.Count};imports={r.Imports.Count};applied={r.Applied.ToString().ToLowerInvariant()};envelope={r.Envelope?.Id??"none"}");foreach(var d in r.Diagnostics)Console.WriteLine($"diagnostic={d.Replace(';',',')}");}else if(f=="human"){Console.WriteLine($"Agent: {r.Status}; envelope={r.Envelope?.Id??"none"}; imports={r.Imports.Count}");foreach(var d in r.Diagnostics)Console.WriteLine(d);}else return 2;return r.ExitCode;}
 private static Option<string>Repo()=>new("--repo"){DefaultValueFactory=_=>Directory.GetCurrentDirectory()};private static Option<string>Format()=>new("--format"){DefaultValueFactory=_=>"human"};
}
