using System.Security.Cryptography;using System.Text;using System.Text.Json;using Cis.Abstractions;
namespace Cis.Modules.Diagnostics;
public sealed record DiagnosticSource(string Id,string Kind,string Location,bool Enabled,bool Sensitive);
public sealed record DiagnosticEvent(string Source,string Severity,string Message,string Evidence,int Line);
public sealed record DiagnosticAnalysis(string CapturedAtUtc,string InputDigest,IReadOnlyList<DiagnosticEvent> Events,IReadOnlyDictionary<string,int> Counts);
public sealed record DiagnosticsResult(string Status,string?RepositoryPath,IReadOnlyList<DiagnosticSource>Sources,IReadOnlyList<DiagnosticEvent>Events,DiagnosticAnalysis?Analysis,IReadOnlyList<string>Errors,bool Applied){public int ExitCode=>Errors.Count>0?4:0;}
public sealed class DiagnosticsService
{public const string AnalysisPath=".cis/local/diagnostics/analysis.json";private static readonly JsonSerializerOptions J=new(JsonSerializerDefaults.Web){WriteIndented=true};private readonly ICisRepositoryContextResolver _resolver;private readonly Func<DateTimeOffset>_clock;public DiagnosticsService(ICisRepositoryContextResolver r,Func<DateTimeOffset>?c=null){_resolver=r;_clock=c??(()=>DateTimeOffset.UtcNow);}
 public DiagnosticsResult Sources(string repo)=>Read(repo,0,null,false);public DiagnosticsResult Summary(string repo)=>Read(repo,500,null,false);public DiagnosticsResult Events(string repo,string?source,int limit)=>Read(repo,Math.Clamp(limit,1,5000),source,false);public DiagnosticsResult Tail(string repo,string source,int lines)=>Read(repo,Math.Clamp(lines,1,1000),source,false);
 public DiagnosticsResult Analyse(string repo){var r=Read(repo,5000,null,false);if(r.RepositoryPath is null||r.Errors.Count>0)return r;var digest=Sha(string.Join("\n",r.Events.Select(x=>$"{x.Source}|{x.Severity}|{x.Message}")));var analysis=new DiagnosticAnalysis(_clock().ToUniversalTime().ToString("O"),digest,r.Events,r.Events.GroupBy(x=>x.Severity,StringComparer.OrdinalIgnoreCase).ToDictionary(x=>x.Key,x=>x.Count(),StringComparer.OrdinalIgnoreCase));var path=Path.Combine(r.RepositoryPath,AnalysisPath.Replace('/',Path.DirectorySeparatorChar));Directory.CreateDirectory(Path.GetDirectoryName(path)!);Write(path,JsonSerializer.Serialize(analysis,J));return r with{Status="analysed",Analysis=analysis,Applied=true};}
 private DiagnosticsResult Read(string repo,int limit,string?selected,bool includeDisabled){var rr=_resolver.Resolve(repo);if(!rr.IsSuccess||rr.Context is null)return new("invalid-repository",null,[],[],null,rr.Errors,false);var c=rr.Context;var sources=Profile(c);var events=new List<DiagnosticEvent>();var errors=new List<string>();foreach(var s in sources.Where(x=>(x.Enabled||includeDisabled)&&(selected is null||x.Id.Equals(selected,StringComparison.OrdinalIgnoreCase)))){if(s.Sensitive){errors.Add($"Source '{s.Id}' is marked sensitive and requires a redacted export before CIS can read it.");continue;}var path=Path.GetFullPath(Path.Combine(c.RepositoryPath,s.Location.Replace('/',Path.DirectorySeparatorChar)));if(!Within(c.RepositoryPath,path)){errors.Add($"Source '{s.Id}' escapes the repository.");continue;}if(!File.Exists(path))continue;var all=File.ReadLines(path).TakeLast(limit==0?0:limit).ToArray();for(var i=0;i<all.Length;i++){var line=all[i];var severity=line.Contains("exception",StringComparison.OrdinalIgnoreCase)||line.Contains("error",StringComparison.OrdinalIgnoreCase)?"error":line.Contains("warn",StringComparison.OrdinalIgnoreCase)||line.Contains("timeout",StringComparison.OrdinalIgnoreCase)?"warning":"info";events.Add(new(s.Id,severity,Redact(line),$"{s.Location}:{i+1}",i+1));}}
  DiagnosticAnalysis?analysis=null;var ap=Path.Combine(c.RepositoryPath,AnalysisPath.Replace('/',Path.DirectorySeparatorChar));if(File.Exists(ap))try{analysis=JsonSerializer.Deserialize<DiagnosticAnalysis>(File.ReadAllText(ap),J);}catch(JsonException){errors.Add("Stored diagnostics analysis is invalid; rerun analyse.");}return new(errors.Count>0?"warnings":"available",c.RepositoryPath,sources,events,analysis,errors,false);}
 private static IReadOnlyList<DiagnosticSource>Profile(CisRepositoryContext c){var p=Path.Combine(c.DocumentationPath,"references","diagnostics-profile.md");if(!File.Exists(p))return[];var output=new List<DiagnosticSource>();foreach(var line in File.ReadLines(p)){if(!line.TrimStart().StartsWith('|'))continue;var x=line.Trim().Trim('|').Split('|').Select(v=>v.Trim()).ToArray();if(x.Length<5||x[0].Equals("Source",StringComparison.OrdinalIgnoreCase)||x.All(v=>v.All(ch=>ch is '-' or ':' or ' ')))continue;output.Add(new(x[0],x[1],x[2],Yes(x[3]),Yes(x[4])));}return output;}
 private static bool Yes(string x)=>x.Equals("yes",StringComparison.OrdinalIgnoreCase)||x.Equals("true",StringComparison.OrdinalIgnoreCase);private static bool Within(string r,string p)=>p.StartsWith(Path.GetFullPath(r).TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase);private static string Redact(string x){var value=x;foreach(var key in new[]{"token","password","secret","authorization","api_key"}){var at=value.IndexOf(key,StringComparison.OrdinalIgnoreCase);if(at>=0){var end=value.IndexOfAny([' ',';',','],at+key.Length);if(end<0)end=value.Length;value=value[..at]+key+"=[REDACTED]"+value[end..];}}return value.Length>1000?value[..1000]:value;}private static string Sha(string x)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(x))).ToLowerInvariant();private static void Write(string p,string x){var t=p+".tmp";File.WriteAllText(t,x);File.Move(t,p,true);}}
